INSERT INTO `config` (`config_id`, `config_group_name`, `config_key`, `config_value`) VALUES
(NULL, 'global.site.meta', 'keywords', 's:23:"portal internetowy demo";'),
(NULL, 'global.site.meta', 'description', 's:23:"portal internetowy demo";'),
(NULL, 'global.site.meta', 'robots', 's:3:"all";'),
(NULL, 'global.site', 'disabled', 's:1:"0";'),
(NULL, 'global.site', 'disabled_text', 's:42:"<p>Prace konserwacyjne - przepraszamy</p>\n";'),
(NULL, 'global.layout', 'home_header_text', 's:32:"AkoPortal - więcej niż portal!";'),
(NULL, 'global.layout', 'copyright_text', 's:31:"AkoPortal - więcej niż portal";'),
(NULL, 'global.layout.cookie_alert', 'enabled', 's:1:"1";'),
(NULL, 'global.layout.cookie_alert', 'text', 's:304:"<p>Ta strona używa plik&oacute;w cookies. Korzystając z tej&nbsp;strony wyrażasz zgodę na używanie cookies, zgodnie z aktualnymi ustawieniami przeglądarki.&nbsp;Jeżeli nie wyrażasz zgody - zmień ustawienia swojej&nbsp;przeglądarki.&nbsp;Dowiedz się więcej z naszej polityki prywatności.</p>\n";'),
(NULL, 'global.payment.dotpay.sms', 'enabled', 's:1:"1";'),
(NULL, 'global.payment.dotpay.sms', 'client_id', 's:5:"44444";'),
(NULL, 'global.payment.dotpay.sms', 'delete_codes', 's:1:"0";'),
(NULL, 'global.payment.dotpay.sms.texts', 'default', 's:54:"<p>Płatność za: %title%</p>\n\n<p>Koszt: %price%</p>\n";'),
(NULL, 'global.payment.dotpay.sms.texts', 'details', 's:511:"<p>Płatność za usługę:&nbsp;%title%</p>\n\n<p>Wyślij sms pod nr %konektor% o treści %service_id% aby otrzymać kod promocyjny. Koszt smsa %price% (brutto)&nbsp;</p>\n\n<p>&nbsp;</p>\n\n<p>Płatności SMS obsługiwane są przez firmę DotPay.pl Usługa SMS dostępna w sieciach Era, Orange, Plus GSM, Play (Sami Swoi, Hayah, Tak Tak, Simplus, Orange Go, POP i inne. Serwis SMS obsługuje DotPay. <a href="http://www.dotpay.pl/pliki/regulaminy/dotpay_regulamin_uslug_sms_20110401.pdf">Regulamin usługi</a>.</p>\n";'),
(NULL, 'global.payment.dotpay.online', 'enabled', 's:1:"1";'),
(NULL, 'global.payment.dotpay.online', 'client_id', 's:5:"44444";'),
(NULL, 'global.payment.dotpay.online', 'delete_codes', 's:1:"0";'),
(NULL, 'global.payment.dotpay.online.texts', 'default', 's:64:"<p>Płatność za:&nbsp;%title%</p>\n\n<p>Koszt:&nbsp;%price%</p>\n";'),
(NULL, 'global.payment.dotpay.online.texts', 'details', 's:156:"<p>Płatność za:&nbsp;%title%</p>\n\n<p>Aby dokonać płatności wejdź pod następujący adres: %link% Koszt ogłoszenia PREMIUM PLUS - %price% brutto</p>\n";'),
(NULL, 'global.payment.payu.online', 'enabled', 's:1:"0";'),
(NULL, 'global.payment.payu.sms', 'enabled', 's:1:"0";'),
(NULL, 'global.payment.paypal.online', 'enabled', 's:1:"0";'),
(NULL, 'global.payment.transfer', 'enabled', 's:1:"1";'),
(NULL, 'global.payment.transfer', 'bank_account_number', 's:24:"123123123123123123123123";'),
(NULL, 'global.payment.transfer', 'address_information', 's:128:"AkoSoft.pl \nul. przykładowa 1\n39-399 Demo\n\nTo są przykładowe dane płatności w wersji demo. Proszę nie opłacać usługi!!!";'),
(NULL, 'global.payment.transfer.texts', 'default', 's:64:"<p>Płatność za:&nbsp;%title%</p>\n\n<p>Koszt:&nbsp;%price%</p>\n";');
